services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - crawler_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - crawler_network
    
  redis:
    image: redis:7.0.12-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - crawler_network
  
  mongo:
    image: mongo:6.0.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - crawler_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    networks:
      - crawler_network

  fetcher_service:
    build:
      context: ./crawler-services/fetcher
    container_name: fetcher_service
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - START_URLS=https://www.seikowatches.com/in-en
    networks:
      - crawler_network
    command: scrapy crawl fetcher_spider

  parser_service:
    build:
      context: ./crawler-services/parser
    container_name: parser_service
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - crawler_network
  
  storage_service:
    build:
      context: ./crawler-services/storage
    container_name: storage_service
    depends_on:
      - kafka
      - mongo
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=web_crawler
      - MONGO_COLLECTION_NAME=pages
    networks:
      - crawler_network

networks:
  crawler_network:
    driver: bridge